name: google_play_scraper
description: A package to get app information from Google Play Store
version: 0.0.5
homepage: https://github.com/shhossain/google_play_scraper

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  html_unescape: ^2.0.0
  http: ^0.13.4

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.2
