name: google_play_scraper
description: Google Play Scraper for flutter and dart helps you to get apks information from google play store
version: 0.0.12
homepage: https://github.com/shhossain/google_play_scraper

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  html_unescape: ^2.0.0
  http: ^0.13.4

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  lints: ">=1.0.1 <3.0.0"
  test: ^1.21.2
