name: google_play_scraper
description: Scraper google play store apps data
version: 0.0.2
homepage: https://github.com/shhossain/google_play_scraper

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  html_unescape: ^2.0.0
  http: ^0.13.4

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
